#!/usr/bin/python3

def raise_exception_msg(message=""):
    """Raise name error with message within a function"""
    raise NameError(message)
